In [1]:
import sys
sys.path.append('C:\\Users\\Danilo Santos\\Desktop\\Qualificação PPGCC\\abordagem\\RFNS')
from grimoire.BaseEnginnering import BaseEnginnering

In [2]:
import pandas as pd

import numpy as np

from sklearn.model_selection import train_test_split

In [3]:
df_acute = pd.read_csv('../datasets/acute/diagnosis.csv',
                       engine='c', 
                       memory_map=True, 
                       low_memory=True)

In [4]:
X = df_acute[['temperatura', 'nausea', 'dorlombar', 
              'urinepushing', 'miccao', 'queimacao', 'inflamacao']]
# Labels
y = df_acute['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, 
                                                    random_state=100, 
                                                    shuffle=True, 
                                                    stratify=y)

In [5]:
# testa com enginnering
model = BaseEnginnering()
model.train_X = X_train
model.train_y = y_train
print('Shape X: ', model.train_X.shape)
print('Shape y:', model.train_y.shape)
model.train_X.head()

Shape X:  (84, 7)
Shape y: (84,)

     temperatura nausea dorlombar urinepushing miccao queimacao inflamacao
106         41.1    yes       yes          yes    yes        no        yes
91          40.6    yes       yes           no    yes        no         no
32          37.2     no       yes           no     no        no         no
95          40.7    yes       yes           no    yes        no         no
31          37.2     no        no          yes    yes        no        yes

In [ ]:
# habilita a codificação dos dados (X)
model.encoder_enable = True
model.encoder_data = True
print('Shape Before: ', model.train_X.shape)
model.get_transform()
print('Shape After: ', model.train_X.shape)
print(model.train_X)

In [6]:
# habilita a codificação do alvo (y)
model.encoder_enable = True
model.encoder_target = True
print('Shape y Before: ', model.train_y.shape)
print(model.train_y)
print(type(model.train_y))
model.get_transform()
print('Shape y After: ', model.train_y.shape)
print(model.train_y)

Shape y Before:  (84,)
106    yes
91     yes
32      no
95     yes
31      no
46      no
37      no
22      no
45      no
74      no
38      no
93     yes
117    yes
57      no
5       no
50      no
97     yes
28      no
81     yes
17      no
89     yes
13      no
27      no
55      no
80      no
101    yes
79     yes
30      no
109    yes
99     yes
      ...
42      no
40      no
78     yes
90      no
114    yes
23      no
25      no
118    yes
19      no
58      no
39      no
98     yes
4       no
41      no
103    yes
65     yes
18      no
94      no
54      no
64     yes
20      no
12      no
7       no
104    yes
44      no
6       no
84     yes
21      no
119    yes
51      no
Name: target, Length: 84, dtype: object
<class 'pandas.core.series.Series'>
Shape y After:  (84,)
106    1
91     1
32     0
95     1
31     0
46     0
37     0
22     0
45     0
74     0
38     0
93     1
117    1
57     0
5      0
50     0
97     1
28     0
81     1
17     0
89     1
13     0
27     0
55     0
80     0
101    1
79     1
30     0
109    1
99     1
      ..
42     0
40     0
78     1
90     0
114    1
23     0
25     0
118    1
19     0
58     0
39     0
98     1
4      0
41     0
103    1
65     1
18     0
94     0
54     0
64     1
20     0
12     0
7      0
104    1
44     0
6      0
84     1
21     0
119    1
51     0
Length: 84, dtype: int32

In [ ]:
X_train.index